name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'rust_qr' # Specify the subdirectory path where you want to check out the code

    - name: Build
      working-directory: ./rust_qr # Set the working directory to the subdirectory
      run: cargo build --verbose

    - name: Run tests
      working-directory: ./rust_qr # Set the working directory to the subdirectory
      run: cargo test --verbose
